[paths]
mgba_dev = "C:/Users/Josh/repos/pokebotswana/mGBA-build-2025-07-15-win32-8840-62070f11d5c8b9c55c53479c7e133d06ca676323/mGBA.exe"

[paths.roms]
pokemon_red = "C:/Users/Josh/repos/pokebotswana/roms/Pokemon - Fire Red Version (U) (V1.1).zip"

[paths.scripts]
server = "C:/Users/Josh/repos/pokebotswana/mgba_scripts/server.lua"
input_display = "C:/Users/Josh/repos/pokebotswana/mgba_scripts/input_display.lua"