[paths]
temp = "C:/Users/Josh/repos/pokebotswana/temp/"
mgba_dev = "C:/Users/Josh/repos/pokebotswana/mGBA-build-2025-07-15-win32-8840-62070f11d5c8b9c55c53479c7e133d06ca676323/mGBA.exe"
state_manager = "C:/Users/Josh/repos/pokebotswana/temp/pkbt_app_state.json"

[paths.roms]
pokemon_red = "C:/Users/Josh/repos/pokebotswana/roms/Pokemon - Fire Red Version (U) (V1.1).zip"
pokemon_sapphire = "C:/Users/Josh/repos/pokebotswana/roms/Pokemon - Sapphire Version (U) (V1.1).zip"
pokemon_emerald = "C:/Users/Josh/repos/pokebotswana/roms/Pokemon - Emerald Version (U).zip"

[paths.scripts]
server = "C:/Users/Josh/repos/pokebotswana/mgba_scripts/server.lua"
input_display = "C:/Users/Josh/repos/pokebotswana/mgba_scripts/input_display.lua"