[paths]
mgba_dev = "C:/Users/Josh/repos/pokebotswana/mGBA-build-2025-07-15-win32-8840-62070f11d5c8b9c55c53479c7e133d06ca676323/mGBA.exe"
pokemon_red_rom = "C:/Users/Josh/repos/pokebotswana/roms/Pokemon - Fire Red Version (U) (V1.1).zip"